/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery_store;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Insets;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author WALTON
 */
public class Product_Detail extends javax.swing.JPanel {

    /**
     * Creates new form Product_Detail
     */
    public static int Order_Id ; 
    public Product_Detail() {
        initComponents();
    }
    public Product_Detail(int order_id){
        this.Order_Id = order_id;
        initComponents();
        Display();
    }

    ArrayList<String> Productname = new Checkout_Items().getProductName();
    ArrayList<String> Productunit = new Checkout_Items().getProductUnit();
    ArrayList<String> ProductImage = new Checkout_Items().getProductImage();
    ArrayList<String> ProductPrice = new Checkout_Items().getProductPrice();

    public void Display(){
        try{
            
            GridBagConstraints gb = new GridBagConstraints(); 
            gb.insets = new Insets(15,15,15,15);
            int y=0;
            gb.gridx = 0;
            gb.gridy = y;
            y++;
            
            FileReader filereader = new FileReader("Buyers.csv");
            CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();
            List<String[]> All_order_info = reader.readAll();
            int col = 0;
            for(String s:All_order_info.get(Order_Id-1)){
                col++;
                if(col<3) continue;
                if(Integer.valueOf(s) <= 0) continue;
                Product_detail_subpanel pds = new Product_detail_subpanel();
                ImageIcon img = new ImageIcon(new ImageIcon(getClass().getResource(ProductImage.get(col-3))).getImage().getScaledInstance(110, 145, Image.SCALE_SMOOTH));
                pds.setImage(img);
                pds.setProductName(Productname.get(col-3));
                pds.setQuantity("X " + s);
                pds.setPrice(ProductPrice.get(col-3));
                pds.setUnit(Productunit.get(col-3));
                pds.setTotalPrice(String.valueOf(Integer.valueOf(ProductPrice.get(col-3)) * Integer.valueOf(s)));
                Subpanel.add(pds,gb);
                gb.gridx = 0;
                gb.gridy = y;
                y++;
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Total_Cost = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Products_count = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Subpanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 247, 243));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        Total_Cost.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        Total_Cost.setText("Total Cost : ");

        Quantity.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        Quantity.setText("Quantity : ");

        Products_count.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        Products_count.setText("Products Count : ");

        Subpanel.setBackground(new java.awt.Color(255, 247, 243));
        Subpanel.setInheritsPopupMenu(true);
        Subpanel.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(Subpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Total_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(Products_count, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Products_count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void setProductCount(String s){
        Products_count.setText(s);
    }
    public void setQuantity(String s){
        Quantity.setText(s);
    }
    public void setTotalCost(String s){
        Total_Cost.setText(s);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Products_count;
    private javax.swing.JLabel Quantity;
    private javax.swing.JPanel Subpanel;
    private javax.swing.JLabel Total_Cost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
