/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery_store;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Win-10
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null); // center form when open        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Last_name = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        First_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Mobile_number = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SignIn_label = new javax.swing.JLabel();
        SignUp_button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(430, 580));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 247, 243));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Sign Up");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("Email : ");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 102));
        jLabel6.setText("Password : ");

        Last_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Last_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Last_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Last_nameFocusLost(evt);
            }
        });
        Last_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Last_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Last_nameMouseExited(evt);
            }
        });
        Last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_nameActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        Password.setToolTipText("");
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Password.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PasswordMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PasswordMouseMoved(evt);
            }
        });
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordMouseExited(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Username : ");

        Username.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameMouseExited(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("First name : ");

        First_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        First_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        First_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                First_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                First_nameFocusLost(evt);
            }
        });
        First_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                First_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                First_nameMouseExited(evt);
            }
        });
        First_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_nameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("Last name : ");

        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(251, 0, 51)));
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmailMouseExited(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 102));
        jLabel11.setText("Mobile number : ");

        Mobile_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(251, 0, 51)));
        Mobile_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Mobile_numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Mobile_numberFocusLost(evt);
            }
        });
        Mobile_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mobile_numberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mobile_numberMouseExited(evt);
            }
        });
        Mobile_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobile_numberActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Already have an account?");

        SignIn_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignIn_label.setForeground(new java.awt.Color(255, 0, 51));
        SignIn_label.setText("Sign In");
        SignIn_label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        SignIn_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignIn_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignIn_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignIn_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignIn_labelMouseExited(evt);
            }
        });

        SignUp_button.setBackground(new java.awt.Color(255, 0, 0));
        SignUp_button.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        SignUp_button.setForeground(new java.awt.Color(255, 255, 255));
        SignUp_button.setText("Sign Up");
        SignUp_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        SignUp_button.setBorderPainted(false);
        SignUp_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUp_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUp_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUp_buttonMouseExited(evt);
            }
        });
        SignUp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SignUp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(227, 227, 227)
                            .addComponent(jLabel2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabel12)
                            .addGap(6, 6, 6)
                            .addComponent(SignIn_label))))
                .addGap(202, 202, 202))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(SignUp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(SignIn_label))))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 620, 710));

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-shop.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Elephant", 3, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vai Brothers Store ");

        jLabel8.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome to ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 710));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void First_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void Mobile_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobile_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberActionPerformed

    private void SignIn_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_labelMouseClicked
       new SignIn().setVisible(true);
       dispose();
    }//GEN-LAST:event_SignIn_labelMouseClicked

    private void SignIn_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_labelMouseEntered
        Border signin_border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        SignIn_label.setBorder(signin_border);        
    }//GEN-LAST:event_SignIn_labelMouseEntered

    private void SignIn_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_labelMouseExited
        Border signin_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
        SignIn_label.setBorder(signin_border);
    }//GEN-LAST:event_SignIn_labelMouseExited

    private void SignUp_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_buttonMouseEntered
        SignUp_button.setForeground(Color.white);
        SignUp_button.setBackground(Color.BLACK);
                
    }//GEN-LAST:event_SignUp_buttonMouseEntered

    private void SignUp_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_buttonMouseExited
        SignUp_button.setForeground(Color.white);
        SignUp_button.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_SignUp_buttonMouseExited

    private void SignUp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_buttonActionPerformed

    private void PasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseMoved
    }//GEN-LAST:event_PasswordMouseMoved

    private void PasswordMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseDragged
    }//GEN-LAST:event_PasswordMouseDragged

    private void PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Password.setBorder(border);
    }//GEN-LAST:event_PasswordMouseEntered

    private void PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseExited
       Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
       Password.setBorder(border);
    }//GEN-LAST:event_PasswordMouseExited

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed

    }//GEN-LAST:event_PasswordKeyPressed

    private void Mobile_numberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mobile_numberMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Mobile_number.setBorder(border);
    }//GEN-LAST:event_Mobile_numberMouseEntered

    private void Mobile_numberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mobile_numberMouseExited
       Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
       Mobile_number.setBorder(border);
    }//GEN-LAST:event_Mobile_numberMouseExited

    private void EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Email.setBorder(border);
    }//GEN-LAST:event_EmailMouseEntered

    private void EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseExited
       Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
       Email.setBorder(border);
    }//GEN-LAST:event_EmailMouseExited

    private void EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyPressed

    }//GEN-LAST:event_EmailKeyPressed

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped

    }//GEN-LAST:event_EmailKeyTyped

    private void EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyReleased

    }//GEN-LAST:event_EmailKeyReleased

    private void Last_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Last_nameMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Last_name.setBorder(border);
    }//GEN-LAST:event_Last_nameMouseEntered

    private void Last_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Last_nameMouseExited
        Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        Last_name.setBorder(border);
    }//GEN-LAST:event_Last_nameMouseExited

    private void First_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_First_nameMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        First_name.setBorder(border);
    }//GEN-LAST:event_First_nameMouseEntered

    private void First_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_First_nameMouseExited
        Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        First_name.setBorder(border);
    }//GEN-LAST:event_First_nameMouseExited

    private void UsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Username.setBorder(border);
    }//GEN-LAST:event_UsernameMouseEntered

    private void UsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseExited
        Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        Username.setBorder(border);
    }//GEN-LAST:event_UsernameMouseExited

    private void SignUp_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_buttonMouseClicked
        if("".equals(Username.getText().trim()) || 
           "".equals(First_name.getText().trim()) || 
           "".equals(Last_name.getText().trim()) || 
           "".equals(Email.getText().trim()) || 
           "".equals(Mobile_number.getText().trim()) || 
           "".equals(Password.getText().trim()))
        {
            JOptionPane.showMessageDialog(this, "Please Fill up the form completely!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
           String mobile = Mobile_number.getText().trim();
           if(Password.getText().length()<6){
               JOptionPane.showMessageDialog(this, "Password must be at least of length 6!", "ERROR", JOptionPane.ERROR_MESSAGE);
           }
           else{
               char m[] = mobile.toCharArray();
               if(mobile.length()>11 || mobile.length()<11){
                   JOptionPane.showMessageDialog(this, "Invalid Mobile Number.Mobile number must be 11 digits!", "ERROR", JOptionPane.ERROR_MESSAGE);
               }
               if(mobile.length()==11){
                    boolean flag=true;
                    if(m[0]=='0' && m[1]=='1'){
                        for(int i=2;i<mobile.length();i++){
                            int temp = Integer.valueOf(m[i])-48;
                            if(temp >=0 && temp<=9) flag=true;
                            else{
                                flag=false;
                                break;
                            }
                        }
                        if(flag==false){
                        JOptionPane.showMessageDialog(this, "Mobile number must contain digits!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            char e[] = Email.getText().trim().toCharArray();
                            flag=false;
                            for(int i=0;i<Email.getText().length();i++){
                                if(e[i]=='@'){
                                    flag= true;
                                    break;
                                }
                            }
                            if(flag==false){
                                JOptionPane.showMessageDialog(this, "Invalid Email id !", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                int P = new Create_record().Record(Username.getText(), First_name.getText(), Last_name.getText(), Email.getText(), Mobile_number.getText(), Password.getText());
                                if(P==0){
                                    JOptionPane.showMessageDialog(this, "The username is taken.Try another", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                                else if(P==1){
                                    JOptionPane.showMessageDialog(this, "Email already been used", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                                else{
                                    new SignIn().setVisible(true);
                                    dispose();
                                }

                            }
                        }
                    }
                    else  JOptionPane.showMessageDialog(this, "Invalid Mobile number!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    
               }
               

            }
        }

    }//GEN-LAST:event_SignUp_buttonMouseClicked
   
    
    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         Username.setBorder(border);
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         Username.setBorder(border);
    }//GEN-LAST:event_UsernameFocusLost

    private void First_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_First_nameFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         First_name.setBorder(border);
    }//GEN-LAST:event_First_nameFocusGained

    private void First_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_First_nameFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         First_name.setBorder(border);
    }//GEN-LAST:event_First_nameFocusLost

    private void Last_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Last_nameFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         Last_name.setBorder(border);
    }//GEN-LAST:event_Last_nameFocusGained

    private void Last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Last_nameFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         Last_name.setBorder(border);
    }//GEN-LAST:event_Last_nameFocusLost

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         Email.setBorder(border);
    }//GEN-LAST:event_EmailFocusGained

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         Email.setBorder(border);
    }//GEN-LAST:event_EmailFocusLost

    private void Mobile_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Mobile_numberFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         Mobile_number.setBorder(border);
    }//GEN-LAST:event_Mobile_numberFocusGained

    private void Mobile_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Mobile_numberFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         Mobile_number.setBorder(border);
    }//GEN-LAST:event_Mobile_numberFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
         Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         Password.setBorder(border);
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
         Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
         Password.setBorder(border);
    }//GEN-LAST:event_PasswordFocusLost
  
 

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField First_name;
    private javax.swing.JTextField Last_name;
    private javax.swing.JTextField Mobile_number;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SignIn_label;
    private javax.swing.JButton SignUp_button;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
