/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery_store;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Win-10
 */
public class User_Information_Frame extends javax.swing.JFrame {

    /**
     * Creates new form User_Information_Frame
     */
    public User_Information_Frame() {
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));   
        initComponents();
        Display();
        
    }

    private static String Name ;
    private static String U_name;
    public void getUName(String name) {
        if(name==null)username_label.setText("Guest");
        else{ 
            String n ;
            char name_array[] = name.toCharArray();
            name_array[0] = Character.toUpperCase(name_array[0]);
            U_name = String.valueOf(name_array);
            username_label.setText(U_name);
            Name = name.toUpperCase();
        }
        if(Name==null){
            SignIn_Out.setText("Sign In");
        }
        else{
            SignIn_Out.setText("Sign Out");
        }
    }
    
    
    
    public void Display(){
        getUName(U_name);
        ImageIcon cart = new ImageIcon(new ImageIcon(getClass().getResource("/images/add_to_cart.png")).getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT));
        add_to_cart_label.setIcon(cart);
        boolean flag=false;
        try{
           FileReader filereader = new FileReader("user_information.csv");
           CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
           List<String[]> Users = reader.readAll();
           ArrayList<String> user_info = new ArrayList<String>(); 
           for(String[] user:Users){
               System.out.println("user[0] " + user[0].toUpperCase());
                 if(user[0].toUpperCase().equals(Name)){
                     Username.setText(user[0]);
                     First_name.setText(user[1]);
                     Last_name.setText(user[2]);
                     Email.setText(user[3]);
                     Mobile_number.setText("0" + user[4]);
                     Password.setText(user[5]);
                     
                     
                     flag=true;
                 }
            }
         
           
        }
        catch(IOException e){
            e.printStackTrace(); 
        }
        catch(CsvException e){
            e.printStackTrace();
        }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Last_name = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Mobile_number = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        First_name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        header_label1 = new javax.swing.JLabel();
        add_to_cart_label = new javax.swing.JLabel();
        SignIn_Out = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        Order_2 = new javax.swing.JLabel();
        Order_1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 247, 243));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Username : ");

        Email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmailMouseExited(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("First Name :");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("User Information");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("Last Name :");

        Last_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Last_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Last_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Last_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Last_nameFocusLost(evt);
            }
        });
        Last_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Last_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Last_nameMouseExited(evt);
            }
        });
        Last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_nameActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordMouseExited(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Mobile_number.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Mobile_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Mobile_number.setMaximumSize(new java.awt.Dimension(0, 19));
        Mobile_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Mobile_numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Mobile_numberFocusLost(evt);
            }
        });
        Mobile_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mobile_numberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mobile_numberMouseExited(evt);
            }
        });
        Mobile_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobile_numberActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 102));
        jLabel15.setText("Email :");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 102));
        jLabel16.setText("Mobile Number :");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 102));
        jLabel17.setText("Password :");

        Update.setBackground(new java.awt.Color(255, 0, 0));
        Update.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        Update.setBorderPainted(false);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameMouseExited(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        First_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        First_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 51)));
        First_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                First_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                First_nameFocusLost(evt);
            }
        });
        First_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                First_nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                First_nameMouseExited(evt);
            }
        });
        First_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(First_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        header_label1.setFont(new java.awt.Font("Elephant", 2, 14)); // NOI18N
        header_label1.setForeground(new java.awt.Color(255, 255, 255));
        header_label1.setText("Vai  Brothers  Store ");
        header_label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                header_label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                header_label1MouseEntered(evt);
            }
        });

        add_to_cart_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_to_cart_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_to_cart_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_to_cart_labelMouseClicked(evt);
            }
        });

        SignIn_Out.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        SignIn_Out.setForeground(new java.awt.Color(255, 255, 255));
        SignIn_Out.setText("Sign Out");
        SignIn_Out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignIn_Out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignIn_OutMouseClicked(evt);
            }
        });
        SignIn_Out.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SignIn_OutComponentShown(evt);
            }
        });

        username_label.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("Guest");
        username_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        username_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                username_labelMouseClicked(evt);
            }
        });
        username_label.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                username_labelComponentShown(evt);
            }
        });

        Order_2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        Order_2.setForeground(new java.awt.Color(255, 255, 255));
        Order_2.setText("Order");
        Order_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Order_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order_2MouseClicked(evt);
            }
        });
        Order_2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Order_2ComponentShown(evt);
            }
        });

        Order_1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        Order_1.setForeground(new java.awt.Color(255, 255, 255));
        Order_1.setText("Details");
        Order_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Order_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order_1MouseClicked(evt);
            }
        });
        Order_1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Order_1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(header_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(username_label)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Order_2)
                    .addComponent(Order_1))
                .addGap(44, 44, 44)
                .addComponent(SignIn_Out)
                .addGap(18, 18, 18)
                .addComponent(add_to_cart_label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_to_cart_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Order_2)
                                .addGap(0, 0, 0)
                                .addComponent(Order_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(header_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SignIn_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 247, 243));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Contact Us");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 51)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 301, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("01674455123");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 0, 0);
        jPanel3.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("vaibrothers@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 608);
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Vai Brothers Store");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 48, 0);
        jPanel3.add(jLabel14, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/call.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 136, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook-logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 136, 48, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gmail.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 136, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_to_cart_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_to_cart_labelMouseClicked
        new Checkout_Items(U_name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_to_cart_labelMouseClicked

    private void SignIn_OutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignIn_OutMouseClicked
        new Items().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignIn_OutMouseClicked

    private void SignIn_OutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SignIn_OutComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_SignIn_OutComponentShown

    private void username_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_labelMouseClicked
        
    }//GEN-LAST:event_username_labelMouseClicked

    private void username_labelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_username_labelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_username_labelComponentShown

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Email.setBorder(border);
    }//GEN-LAST:event_EmailFocusGained

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        Email.setBorder(border);
    }//GEN-LAST:event_EmailFocusLost

    private void EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseEntered
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        Email.setBorder(border);
    }//GEN-LAST:event_EmailMouseEntered

    private void EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseExited
        Border border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        Email.setBorder(border);
    }//GEN-LAST:event_EmailMouseExited

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void Last_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Last_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameFocusGained

    private void Last_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Last_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameFocusLost

    private void Last_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Last_nameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameMouseEntered

    private void Last_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Last_nameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameMouseExited

    private void Last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Last_nameActionPerformed

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordMouseEntered

    private void PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordMouseExited

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void Mobile_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Mobile_numberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberFocusGained

    private void Mobile_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Mobile_numberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberFocusLost

    private void Mobile_numberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mobile_numberMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberMouseEntered

    private void Mobile_numberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mobile_numberMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberMouseExited

    private void Mobile_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobile_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobile_numberActionPerformed

    
    public static ArrayList<String[]> all_user_order_details = new Grocery_Store().getAllUserOrderDetails();
    
    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        if("".equals(Username.getText().trim()) ||
            "".equals(First_name.getText().trim()) ||
            "".equals(First_name.getText().trim()) ||
            "".equals(Email.getText().trim()) ||
            "".equals(Mobile_number.getText().trim()) ||
            "".equals(Password.getText().trim()))
        {
            JOptionPane.showMessageDialog(this, "Please Fill up the form completely!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String mobile = Mobile_number.getText().trim();
            if(Password.getText().length()<6){
                JOptionPane.showMessageDialog(this, "Password must be at least of length 6!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else{
                char m[] = mobile.toCharArray();
                if(mobile.length()>11 || mobile.length()<11){
                    JOptionPane.showMessageDialog(this, "Invalid Mobile Number.Mobile number must be 11 digits!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                if(mobile.length()==11){
                    boolean flag=true;
                    if(m[0]=='0' && m[1]=='1'){
                        for(int i=2;i<mobile.length();i++){
                            int temp = Integer.valueOf(m[i])-48;
                            if(temp >=0 && temp<=9) flag=true;
                            else{
                                flag=false;
                                break;
                            }
                        }
                        if(flag==false){
                            JOptionPane.showMessageDialog(this, "Mobile number must contain digits!", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            char e[] = Email.getText().trim().toCharArray();
                            flag=false;
                            for(int i=0;i<Email.getText().length();i++){
                                if(e[i]=='@'){
                                    flag= true;
                                    break;
                                }
                            }
                            if(flag==false){
                                JOptionPane.showMessageDialog(this, "Invalid Email id !", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                int where=0;
                                try{
                                    FileReader filereader = new FileReader("user_information.csv");
                                    CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
                                    List<String[]> Users = reader.readAll();
                                    for(String[] user:Users){
                                        where++;
                                         if(user[0].toLowerCase().equals(Name.toLowerCase().trim())){                 
                                             break;
                                         }
                                     }
                                }
                                catch(Exception exception){
                                    exception.printStackTrace();
                                }
                                
                                int P=2;
                                try{
                                    System.out.println("Where " + where );
                                    FileReader filereader = new FileReader("user_information.csv");
                                    CSVReader reader = new CSVReaderBuilder(filereader).build();       
                                    List<String[]> Users = reader.readAll();
                                    
                                    int q=0;
                                    for(String[] user:Users){
                                        q++;
                                        if(q==where+1) continue;
                                        if(user[0].toLowerCase().equals(Username.getText().toLowerCase().trim())){
                                             P=0;
                                             break;
                                        }
                                        if(user[3].toLowerCase().equals(Email.getText().toLowerCase().trim())){
                                             P=1;
                                             break;
                                        }                      
                                    }
                                    if(P==2){   
                                        Users.get(where)[0] = Username.getText();
                                        Users.get(where)[1] = First_name.getText();
                                        Users.get(where)[2] = Last_name.getText();
                                        Users.get(where)[3] = Email.getText();
                                        Users.get(where)[4] = Mobile_number.getText();
                                        Users.get(where)[5] = Password.getText();
                                        CSVWriter writer = new CSVWriter(new FileWriter("user_information.csv"));
                                        writer.writeAll(Users);
                                        writer.flush();
                                        writer.close();
                                    }
                                    
                                    String Old_username = username_label.getText();
                                    FileReader filereader1 = new FileReader("Buyers.csv");
                                    CSVReader reader1 = new CSVReaderBuilder(filereader1).build();       
                                    List<String[]> Buyers = reader1.readAll();
                                    
                                    for(int i=1;i<Buyers.size();i++){
                                          if(Buyers.get(i)[0].equals(Old_username)){
                                              Buyers.get(i)[0] = Username.getText();
                                          }
                                    }
                                    CSVWriter writer1 = new CSVWriter(new FileWriter("Buyers.csv"));
                                    writer1.writeAll(Buyers);
                                    writer1.flush();
                                    writer1.close();

                                }
                                catch(IOException exception){
                                    exception.printStackTrace();
                                }
                                catch(CsvException exception){
                                    exception.printStackTrace();
                                }
      
                                if(P==0){
                                    JOptionPane.showMessageDialog(this, "The username is taken.Try another", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                                else if(P==1){
                                    JOptionPane.showMessageDialog(this, "Email already been used", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                                else{
                                    JOptionPane.showMessageDialog(this, "Your profile has been successfully updated", "Updated", JOptionPane.PLAIN_MESSAGE);
                                }

                            }
                        }
                    }
                    else  JOptionPane.showMessageDialog(this, "Invalid Mobile number!", "ERROR", JOptionPane.ERROR_MESSAGE);

                }

            }
        }
    }//GEN-LAST:event_UpdateMouseClicked

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update.setForeground(Color.white);
        Update.setBackground(Color.BLACK);

    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update.setForeground(Color.white);
        Update.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_UpdateMouseExited

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void header_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_label1MouseClicked
        new Items(U_name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_header_label1MouseClicked

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFocusLost

    private void UsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameMouseEntered

    private void UsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameMouseExited

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void First_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_First_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameFocusGained

    private void First_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_First_nameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameFocusLost

    private void First_nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_First_nameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameMouseEntered

    private void First_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_First_nameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameMouseExited

    private void First_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_First_nameActionPerformed

    private void header_label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_label1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_header_label1MouseEntered

    private void Order_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_2MouseClicked
        new Product_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Order_2MouseClicked

    private void Order_2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Order_2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Order_2ComponentShown

    private void Order_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_1MouseClicked
        new Product_Details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Order_1MouseClicked

    private void Order_1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Order_1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Order_1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Information_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Information_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Information_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Information_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Information_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField First_name;
    private javax.swing.JTextField Last_name;
    private javax.swing.JTextField Mobile_number;
    private javax.swing.JLabel Order_1;
    private javax.swing.JLabel Order_2;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel SignIn_Out;
    private javax.swing.JButton Update;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel add_to_cart_label;
    private javax.swing.JLabel header_label1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
